// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpjqbfaieyvgpaioomeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwanFiZmFpZXl2Z3BhaW9vbWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzY1NjUsImV4cCI6MjA2ODcxMjU2NX0.aNeGfwwGg-1CWIgwwnydDb1-eGQGjqLk5q9prBWgnJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});